### ISSUE TITLE
community support

### ISSUE THREAD

**Issue by DavidBruchmann** [clearhealth/clearhealth#1]
the mentioned community seems being dead, the forum is down, the home-page never shows any links, it seems the project never has been updated in git since two years. In short the whole project seems being dead.

**Comment by clearhealth** [comment]
Clearhealth is actively maintained though because of meaningful use versioning it must be certified at each revision. Small incremental changes, which are the typical mainstay of open source in other industries, are discouraged by such a system. The open source edition available here now is compatible with Meaningful use 1 and 2 guideline sets, though you must obtain your own certification or choose to contract for our implementation. The version 5 download which is MU 3 compatible will be available on github here in march 2015. We welcome patches or contributions but have fairly strict guidelines for their inclusion. As a business we work with large institutions and systems rather than individuals or small practices. Thanks for your interest in clearhealth.

-Mark
